# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
name: Docker-CI
trigger:
  - main
    
pool: 
  vmImage: 'ubuntu-latest'

resources:
  - repo: self
    
variables:
  ImageName: 'luifa7/recommendoo_be:$(Build.BuildId)'
  
stages:
  - stage: BuildAndPush
    displayName: Build and push image
    jobs:
      - job: DockerImage
        displayName: Build and push Docker Image
        steps:
          - task: Docker@2
            displayName: Build the Docker image
            inputs:
              containerRegistry: dockerHub
              command: build
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              tag: '$(ImageName)'
              includeLatestTag: true
              useDefaultContext: false
              buildContext: '.'
          - task: Docker@2
            displayName: Push the Docker image to DockerHub
            inputs:
              containerRegistry: dockerHub
              repository: luifa7/recommendoo_be
              command: push
              tag: '$(ImageName)'
            condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
